explicitly convert to double to suppress warnings
with clang-10 on ubuntu 18.04:

In file included from /root/src/flatcc/test/monster_test/monster_test.c:7:
/root/src/flatcc/include/flatcc/support/elapsed.h:19:22: error: implicit conversion from 'long' to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
    return tv.tv_sec - t0.tv_sec + (tv.tv_usec - t0.tv_usec) / 1000000.;
           ~~~~~~~~~~^~~~~~~~~~~ ~
/root/src/flatcc/include/flatcc/support/elapsed.h:19:48: error: implicit conversion from 'long' to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
    return tv.tv_sec - t0.tv_sec + (tv.tv_usec - t0.tv_usec) / 1000000.;
                                    ~~~~~~~~~~~^~~~~~~~~~~~  ~
/root/src/flatcc/include/flatcc/support/elapsed.h:51:54: error: implicit conversion from 'size_t' (aka 'unsigned long') to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
    printf("bandwidth: %.3f (MB/s)\n", (double)rep * size / 1e6 / tdiff);
                                                   ~ ^~~~
3 errors generated.